apiVersion: v2
name: prometheus
description: Prometheus monitoring for chat application
type: application
version: 1.0.0
appVersion: "2.45.0"
dependencies:
  - name: kube-prometheus-stack
    version: "65.8.1"
    repository: "https://prometheus-community.github.io/helm-charts"