{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.fullname" . }}-pvc
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
